### ISSUE TITLE
Addition to nixpkgs

### ISSUE THREAD

**Issue by terlar** [zombiezen/nixcached#23]
Hello, I find this really useful for those who are running on GCP and was lucky to stumble upon it.

I think more people would benefit if it was added to nixpkgs and also perhaps the awesome nix list.

However, I am aware you have withdrawn from nixpkgs and I wonder if you would mind the package being added or not. I would of course take care of that. 

Thanks for this tool once again. Was the simplest most straightforward cache solution for my case.

**Comment by zombiezen** [comment]
I don't mind if you package it for nixpkgs. I appreciate you asking first!
